name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Tests
      run: mvn test
	  - name: Upload JAR Artifact
	       if: github.event_name == 'push' && github.ref == 'refs/heads/master'
	        uses: actions/upload-artifact@v4
	        with:
	          name: helloworld-jar
	          path: target/helloworld-1.0-SNAPSHOT.jar
	      - name: Create GitHub Release
	        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
	        uses: softprops/action-gh-release@v2
	        with:
	          files: target/helloworld-1.0-SNAPSHOT.jar
	          tag_name: v${{ github.run_number }}
	          name: Release v${{ github.run_number }}
	          draft: false
	          prerelease: false
	        env:
	          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}